### ISSUE TITLE
Super agent double callback bug

### ISSUE THREAD

**Issue by shamblid** [CyberSource/cybersource-rest-client-node#12] opened 2019-01-16 19:40 UTC
In implementing the rest client I ran into this error which may be caused by this snippet of code below. I removed it from my own code and I did not run into the bug again. I am using Node 8 with async/await so I am not using callbacks in the first place.

https://github.com/CyberSource/cybersource-rest-client-node/blob/7da378925064a68c7df97dabb0b5634463874a37/src/ApiClient.js#L536-L551

**Comment by Amit-Patel** [comment] 2019-11-18 05:53
Hi @shamblid,

Could you direct me on how I can reproduce the double callback bug using async/await?

Thanks,
Amit

**Comment by gnongsie** [comment] 2019-12-19 10:57
Hi,

I am closing this issue due to non-activity. 

Feel free to open a new issue if there are any doubts.

**Closed by gnongsie** 2019-12-19 10:57 UTC

**Comment by acellam** [comment] 2023-05-17 08:19
This issue was fixed but it has been re-introduced again in the latest released changes
